### ISSUE TITLE
issue while running 

### ISSUE THREAD

**Issue by sketch0x** [BitStore-dev/BitRat#1]
Traceback (most recent call last):
  File "C:\Users\qanet\Downloads\BitRat-BitStore (1)\BitRat-BitStore\BitRat.py", line 19, in <module>
    client = discord.Client()
TypeError: Client.__init__() missing 1 required keyword-only argument: 'intents'

**Comment by chethanyadav456** [comment]
you could use the default Intents unless you have a particular one to specify

`client = discord.Client(intents=discord.Intents.default())`
See [Intents](https://discordpy.readthedocs.io/en/latest/api.html?highlight=client#discord.Intents) for more details

If u stil get the error u can contact me on discord - `Raaz#2233`
